#!/bin/bash


INPUT_FILE=$1
TARGET_HOSTNAME=
TARGET_PORT=
CIPHER_TEMP=./tmp/ciphers
CIPHER_LINE_START=
CIPHER_LINE_END=
OUTPUT_FILE="output.csv"
LIST_COUNT=`cat $1 | wc -l`
COUNTER=1

rm -f ${OUTPUT_FILE}
rm -f ${CIPHER_TEMP}

grep_ciphers () {
        CIPHER_LINE_START=`grep -n "${PROTOCOL}:" ${CIPHER_TEMP} | cut -d':' -f1`
        if [ ! -z "${CIPHER_LINE_START}" ]; then
                CIPHER_LINE_END=`sed -n "/${PROTOCOL}:/,/compressors:/p" ${CIPHER_TEMP} | wc -l`
                let CIPHER_LINE_END=CIPHER_LINE_START+CIPHER_LINE_END-2
                let CIPHER_LINE_START=CIPHER_LINE_START+2
                while [ ${CIPHER_LINE_START} -le ${CIPHER_LINE_END} ];
                do
                        ALGO_TEST=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | grep "("`
                        if [ ! -z "${ALGO_TEST}" ]; then
                                CIPHER=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d' ' -f8`
                                ALGORYTHM=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d'(' -f2 | cut -d')' -f1`
                        else
                                CIPHER=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d' ' -f8`
                                ALGORYTHM=""
                        fi
                        GRADE=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d'-' -f2 | cut -d' ' -f2`
                        echo ${TARGET_HOSTNAME},${TARGET_IP},${TARGET_PORT},${PROTOCOL},${CIPHER},${ALGORYTHM},${GRADE} >> ${OUTPUT_FILE}
                        let CIPHER_LINE_START=CIPHER_LINE_START+1
                done
        else
                echo no > /dev/null
        fi
}


echo "HOSTNAME,IP,PORT,PROTOCOL,CIPHER,ALGORITHM,GRADE" > ${OUTPUT_FILE}

while read line ;do
set TARGET_HOSTNAME
set TARGET_PORT
set TARGET_IP
TARGET_HOSTNAME=`echo $line | cut -d, -f1`
TARGET_PORT=`echo $line | cut -d, -f2`
echo "Collecting ciphers for ${TARGET_HOSTNAME} - ${COUNTER} of ${LIST_COUNT}"
nmap --script ssl-enum-ciphers -p ${TARGET_PORT}  ${TARGET_HOSTNAME} > ${CIPHER_TEMP}
TARGET_IP=`grep "Nmap scan report for " ${CIPHER_TEMP} | cut -d'(' -f2 | cut -d')' -f1`

PROTOCOL="SSLv3"
grep_ciphers

PROTOCOL="TLSv1.0"
grep_ciphers

PROTOCOL="TLSv1.1"
grep_ciphers

PROTOCOL="TLSv1.2"
grep_ciphers

let COUNTER=COUNTER+1
done < ${INPUT_FILE}
