#!/bin/bash


INPUT_FILE=$1
TARGET_HOSTNAME=
TARGET_PORT=
CIPHER_TEMP=./tmp/ciphers
CIPHER_LINE_START=
CIPHER_LINE_END=
OUTPUT_FILE="output.csv"

touch ${OUTPUT_FILE}
rm -f ${OUTPUT_FILE}
touch ${OUTPUT_FILE}

grep_ciphers () {
        CIPHER_LINE_START=`grep -n "${PROTOCOL}" ${CIPHER_TEMP} | cut -d':' -f1`
        if [ ! -z ${CIPHER_LINE_START} ]; then
                CIPHER_LINE_END=`sed -n "/${PROTOCOL}/,/comp/p" ${CIPHER_TEMP} | wc -l`
                let CIPHER_LINE_END=CIPHER_LINE_START+CIPHER_LINE_END-2
                let CIPHER_LINE_START=CIPHER_LINE_START+2
                while [ ${CIPHER_LINE_START} -le ${CIPHER_LINE_END} ];
                do
                        CIPHER=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d' ' -f8`
                        ALGORYTHM=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d'(' -f2 | cut -d')' -f1`
                        GRADE=`sed "${CIPHER_LINE_START}q;d" ${CIPHER_TEMP} | cut -d'-' -f2 | cut -d' ' -f2`
                        echo ${TARGET_HOSTNAME},${TARGET_PORT},${TARGET_IP},${PROTOCOL},${CIPHER},${ALGORYTHM},${GRADE} >> ${OUTPUT_FILE}
                        let CIPHER_LINE_START=CIPHER_LINE_START+1
                done
        else
                echo no > /dev/null
        fi
}


echo "HOSTNAME,PORT,IP,PROTOCOL,CIPHER,ALGORITHM,GRADE" > ${OUTPUT_FILE}

while read line ;do
set TARGET_HOSTNAME
TARGET_HOSTNAME=`echo $line | cut -d, -f1`
TARGET_IP=`grep "Nmap scan report for" ${CIPHER_TEMP} | cut -d'(' -f2 | cut -d')' -f1`
TARGET_PORT="443"
echo "Collecting ciphers for ${TARGET_HOSTNAME}"
nmap --script ssl-enum-ciphers -p 443  ${TARGET_HOSTNAME} > ${CIPHER_TEMP}

PROTOCOL="SSLv3"
grep_ciphers

PROTOCOL="TLSv1.0"
grep_ciphers

PROTOCOL="TLSv1.1"
grep_ciphers

PROTOCOL="TLSv1.2"
grep_ciphers

done < ${INPUT_FILE}
